# Configuration for Kamana Shrestha's GitHub Portfolio

title: Kamana Shrestha
description: Automation Engineer
show_downloads: false
theme: jekyll-theme-architect
avatar: https://github.com/settings/profile.png
